### ISSUE TITLE
Not compatible with the latest version of Thaumic Energistics

### ISSUE THREAD

**Issue by FnTlv** [GTNewHorizons/Applied-Energistics-2-Unofficial#324]
When I combine any element, the client will crash
https://pastes.dev/jcbMhvuvXH
Versions:
thaumicenergistics-1.1.3.0.jar
appliedenergistics2-rv3-beta-211-GTNH.jar

**Comment by firenoo** [comment]
This is likely due to crafting v2. In the config file, set `CraftingCalculatorVersion=1` here:
```
debug {
    I:CraftingCalculatorVersion=1
    B:EnableP2pBackboneTransfer=false
    B:EnableQuantumBridgeBackboneTransfer=false
    B:LogPathFinding=false
    B:LogTiming=false
}
```

**Comment by FnTlv** [comment]
> This is likely due to crafting v2. In the config file, set `CraftingCalculatorVersion=1` here:
> 
> ```
> debug {
>     I:CraftingCalculatorVersion=1
>     B:EnableP2pBackboneTransfer=false
>     B:EnableQuantumBridgeBackboneTransfer=false
>     B:LogPathFinding=false
>     B:LogTiming=false
> }
> ```

I have set the CraftingCalculatorVersion=1, but the error still occurs

**Comment by firenoo** [comment]
After looking through the crash report more closely, and digging through the source code of upstream Thaumic Energistics, I believe it is a problem with Thaumic Energistics - namely, it is using some hacky reflection to access a private field. It is probably not finding it for whatever reason, and thus you get a NullpointerException. Without further information it is difficult to help you. Posting the entire log might be useful.

I'm reluctant to suggest this, but you can try GTNH's fork of thaumic energistics. I do not know if there are GTNH specific changes, nor are we officially offering out-of-pack support for it, so **use at your own risk**.

Make sure to update ae2 to the latest if you use the latest from here: https://github.com/GTNewHorizons/ThaumicEnergistics/releases

I will repeat this again, we will *not* support Thaumic Energistics for non-GTNH packs. If that does not solve the problem, I'm sorry - there's not much we can do from AE2's end, unless someone else chimes in and says otherwise.

**Comment by FnTlv** [comment]
> After looking through the crash report more closely, and digging through the source code of upstream Thaumic Energistics, I believe it is a problem with Thaumic Energistics - namely, it is using some hacky reflection to access a private field. It is probably not finding it for whatever reason, and thus you get a NullpointerException. Without further information it is difficult to help you. Posting the entire log might be useful.
> 
> I'm reluctant to suggest this, but you can try GTNH's fork of thaumic energistics. I do not know if there are GTNH specific changes, nor are we officially offering out-of-pack support for it, so **use at your own risk**.
> 
> Make sure to update ae2 to the latest if you use the latest from here: https://github.com/GTNewHorizons/ThaumicEnergistics/releases
> 
> I will repeat this again, we will _not_ support Thaumic Energistics for non-GTNH packs. If that does not solve the problem, I'm sorry - there's not much we can do from AE2's end, unless someone else chimes in and says otherwise.

Thankfully, after I used GTNH's fork of thaumic energistics, the error doesn't happen anymore.
