### ISSUE TITLE
Is it necessary to add more cell for AE?

### ISSUE THREAD

**Issue by MCTBL** [GTNewHorizons/Applied-Energistics-2-Unofficial#486]
![e8a877ec10df1b623d20bd4abff6fa16](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/30978504/65a03181-34cc-413e-95f0-940025193460)
like 65536K, 262144K and above?

**Comment by Hikari1nVoid** [comment]
Just see what happened when u added quantum&singularity essentials and the answer should be no.

**Comment by MCTBL** [comment]
or change the cell 1024K and above to 1M, 4M, 16M. And create new 64M, 256M etc?

**Comment by boubou19** [comment]
it really is not necessary

**Comment by MCTBL** [comment]
okay

**Comment by Devtron3D** [comment]
I am at UEV stage atm
![image](https://github.com/user-attachments/assets/b5b66a6a-fc07-4b02-8a40-402b5792d970)
Crafts are getting bigger and bigger and the endgame is getting moved, I see server bases where people spamm 1000's of 16mb cells just to keep their ore processing and refinement running,
People also use infinity chests to store mining ore and processed stuff due to the limited size of AE cells.
With the old Fluid modpack we had bigger cells, and I miss those.

Why do we encourage infinity chests usage with AE and 1000's of AE cell storage, when if we had bigger cells, people could store their ore processing in a LOT less amount of cells. Is a wall of 1000s of cells noy bad for server performance?

**Comment by Hikari1nVoid** [comment]
>Why do we encourage infinity chests usage with AE and 1000's of AE cell storage, when if we had bigger cells, people could store their ore processing in a LOT less amount of cells. Is a wall of 1000s of cells not bad for server performance?

You don't have to.

**Comment by Devtron3D** [comment]
> > Why do we encourage infinity chests usage with AE and 1000's of AE cell storage, when if we had bigger cells, people could store their ore processing in a LOT less amount of cells. Is a wall of 1000s of cells not bad for server performance?
> 
> You don't have to.

What other options are there to store massive around of raw ores and then the processed ores?

**Comment by joshaup1999** [comment]
What are you on about, we have quantum and singularity cells already

AE cells only cause performance issues if you're storing stupid amounts of things like armour

**Comment by Reflex18** [comment]
> I am at UEV stage atm ![image](https://private-user-images.githubusercontent.com/3405825/374636109-b5b66a6a-fc07-4b02-8a40-402b5792d970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzMwMDIsIm5iZiI6MTcyODQzMjcwMiwicGF0aCI6Ii8zNDA1ODI1LzM3NDYzNjEwOS1iNWI2NmE2YS1mYzA3LTRiMDItOGE0MC00MDJiNTc5MmQ5NzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDAxMTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTIwNzdiMGI1YTlmYzVlODE4MzQ3MTk4OGYxY2I1ZWYyMDBhZjE3NzMxMzRmMGIzMGNiYmNmZjg0ZmJmM2EyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5ebedPxm2lQBKB6nFIuMV8HPVHCAftgKAADBCz3BiNQ) Crafts are getting bigger and bigger and the endgame is getting moved, I see server bases where people spamm 1000's of 16mb cells just to keep their ore processing and refinement running, People also use infinity chests to store mining ore and processed stuff due to the limited size of AE cells. With the old Fluid modpack we had bigger cells, and I miss those.
> 
> Why do we encourage infinity chests usage with AE and 1000's of AE cell storage, when if we had bigger cells, people could store their ore processing in a LOT less amount of cells. Is a wall of 1000s of cells not bad for server performance?

I just need to know, why do you need 103 million chipped diamonds?

**Comment by Devtron3D** [comment]
> > I am at UEV stage atm ![image](https://private-user-images.githubusercontent.com/3405825/374636109-b5b66a6a-fc07-4b02-8a40-402b5792d970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzMwMDIsIm5iZiI6MTcyODQzMjcwMiwicGF0aCI6Ii8zNDA1ODI1LzM3NDYzNjEwOS1iNWI2NmE2YS1mYzA3LTRiMDItOGE0MC00MDJiNTc5MmQ5NzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDAxMTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTIwNzdiMGI1YTlmYzVlODE4MzQ3MTk4OGYxY2I1ZWYyMDBhZjE3NzMxMzRmMGIzMGNiYmNmZjg0ZmJmM2EyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5ebedPxm2lQBKB6nFIuMV8HPVHCAftgKAADBCz3BiNQ) Crafts are getting bigger and bigger and the endgame is getting moved, I see server bases where people spamm 1000's of 16mb cells just to keep their ore processing and refinement running, People also use infinity chests to store mining ore and processed stuff due to the limited size of AE cells. With the old Fluid modpack we had bigger cells, and I miss those.
> > Why do we encourage infinity chests usage with AE and 1000's of AE cell storage, when if we had bigger cells, people could store their ore processing in a LOT less amount of cells. Is a wall of 1000s of cells not bad for server performance?
> 
> I just need to know, why do you need 103 million chipped diamonds?

![image](https://github.com/user-attachments/assets/bed5f25c-f3a6-4e8e-b02f-e08f668055a6)
Thats why, don't have enough diamonds in stock so it tries to make more out of lesser parts.

**Comment by Devtron3D** [comment]
> What are you on about, we have quantum and singularity cells already
> 
> AE cells only cause performance issues if you're storing stupid amounts of things like armour

That I agree on, what I want to use it for is only two things,   Raw ore, and processed ore,
I don't know if a new type of cell can be created that holds 63 items instead of 1 for the bigger cells, which can only hold ores/processed ores items.

I might have a thought of a new structure that could only hold those ores, so you would at max need two, such a structure could be expensive to build ofcourse, upgradable, but would also need constant power otherwise it would void everything, so if you mess up your power and the internal buffer runs out, all your ores are GONE-
Ill think about this for a few days and the make a new git with a design idea
